development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: desafio_development
  pool: 5
  username: carlos
  password: 1234
  
  
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: carlos
  password: 1234
 